"""
Observability - Unified metrics, tracing, logging, alerting, and health checks.
"""

from .metrics import (
    MetricsRegistry,
    MetricType,
    Counter,
    Gauge,
    Histogram,
    StandardMetrics,
    PrometheusExporter,
    MetricsMiddleware,
    get_metrics_registry,
    get_standard_metrics,
    get_prometheus_exporter,
    create_metrics_registry,
)

from .tracing import (
    Span,
    SpanKind,
    SpanStatus,
    SpanEvent,
    SpanLink,
    SpanContext,
    SpanAttributes,
    InMemoryTracer,
    OTELTracer,
    Tracer,
    TracingContext,
    set_span_attributes,
    add_span_event,
    TracingMiddleware,
    SpanExporter,
    ConsoleSpanExporter,
    JsonSpanExporter,
    create_tracer,
    create_tracing_context,
)

from .logging import (
    LogLevel,
    LogRecord,
    JSONFormatter,
    ConsoleFormatter,
    ContextLogger,
    LoggingManager,
    LogHandler,
    ElasticsearchHandler,
    SyslogHandler,
    LogCorrelation,
    LoggingManager,
    get_logging_manager,
    get_logger,
    get_correlation,
    configure_logging,
    create_logging_manager,
)

from .alerting import (
    AlertSeverity,
    AlertStatus,
    ConditionOperator,
    AlertCondition,
    AlertRule,
    Alert,
    AlertEvaluator,
    AlertManager,
    NotificationChannel,
    WebhookChannel,
    EmailChannel,
    SlackChannel,
    PagerDutyChannel,
    create_alert_manager,
    create_alert_rule,
)

from .health import (
    HealthStatus,
    HealthCheckResult,
    ComponentHealth,
    SystemHealth,
    HealthCheck,
    DatabaseHealthCheck,
    RedisHealthCheck,
    HTTPHealthCheck,
    DiskSpaceCheck,
    MemoryUsageCheck,
    CustomHealthCheck,
    HealthChecker,
    ComponentHealth,
    SystemHealth,
    KubernetesProbes,
    create_health_checker,
    create_kubernetes_probes,
    create_standard_checks,
)

__all__ = [
    # Metrics
    "MetricsRegistry",
    "MetricType",
    "Counter",
    "Gauge",
    "Histogram",
    "StandardMetrics",
    "PrometheusExporter",
    "MetricsMiddleware",
    "get_metrics_registry",
    "get_standard_metrics",
    "get_prometheus_exporter",
    "create_metrics_registry",
    # Tracing
    "Span",
    "SpanKind",
    "SpanStatus",
    "SpanEvent",
    "SpanLink",
    "SpanContext",
    "SpanAttributes",
    "InMemoryTracer",
    "OTELTracer",
    "Tracer",
    "TracingContext",
    "set_span_attributes",
    "add_span_event",
    "TracingMiddleware",
    "SpanExporter",
    "ConsoleSpanExporter",
    "JsonSpanExporter",
    "create_tracer",
    "create_tracing_context",
    # Logging
    "LogLevel",
    "LogRecord",
    "JSONFormatter",
    "ConsoleFormatter",
    "ContextLogger",
    "LoggingManager",
    "LogHandler",
    "ElasticsearchHandler",
    "SyslogHandler",
    "LogCorrelation",
    "LoggingManager",
    "get_logging_manager",
    "get_logger",
    "get_correlation",
    "configure_logging",
    "create_logging_manager",
    # Alerting
    "AlertSeverity",
    "AlertStatus",
    "ConditionOperator",
    "AlertCondition",
    "AlertRule",
    "Alert",
    "AlertEvaluator",
    "AlertManager",
    "NotificationChannel",
    "WebhookChannel",
    "EmailChannel",
    "SlackChannel",
    "PagerDutyChannel",
    "create_alert_manager",
    "create_alert_rule",
    # Health
    "HealthStatus",
    "HealthCheckResult",
    "ComponentHealth",
    "SystemHealth",
    "HealthCheck",
    "DatabaseHealthCheck",
    "RedisHealthCheck",
    "HTTPHealthCheck",
    "DiskSpaceCheck",
    "MemoryUsageCheck",
    "CustomHealthCheck",
    "HealthChecker",
    "ComponentHealth",
    "SystemHealth",
    "KubernetesProbes",
    "create_health_checker",
    "create_kubernetes_probes",
    "create_standard_checks",
]
